### ISSUE TITLE
Bug: Tags with capital letters get spaced out

### ISSUE THREAD

**Issue by onkoe** [ronv/lines#3]
Hello,
When using multiple capital letters in a row on the Lines theme's tags, the letters become weird and space out. Here's approximately how that looks: 
![image](https://user-images.githubusercontent.com/66580279/169162278-9153f8b1-e112-4c4b-8767-10302dd51fd6.png)

The test page had the following code: 
```
---
title: "This is a test post!"
description: "It's a test!"
date: "2022-05-18"
tags:
- Testing
- LineageOS
- normal
- normal words
- CC BY-SA
- woah woah woah
---

test
```

This has occurred on multiple different pages when trying to sort licenses via tag or when writing things like "LineageOS." Any help, judgement, or fixes would be greatly appreciated! Thanks for the great project!

**Comment by ronv** [comment]
Hi, I will check this later! Don't have time now...

**Comment by hexnaught** [comment]
This is due to the call to `humanize` in the partials `tags.html` template.

```html
{{ range $i, $e := .Params.tags -}}
    {{- if $i -}}, {{ end -}}
    <a href='{{ "/tags/" | relLangURL }}{{ . | urlize }}'>{{ $e | humanize }}</a>
{{- end -}}
```

https://gohugo.io/functions/humanize/

----

With the following tags and the pipe to `humanize` in place, the result is:

```yaml
tags:
    - tag 1
    - tag 2
    - THIS IS A TAG
```

![image](https://user-images.githubusercontent.com/1098786/172959228-e8bea4a0-bd50-409e-986d-72159182e434.png)


Removing the pipe to `humanize` results in:

![image](https://user-images.githubusercontent.com/1098786/172959193-fa646142-0c2d-479f-b697-a7259a5298ef.png)

**Comment by ronv** [comment]
@onkoe fixed! thanks @hexnaught 😄
